# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/IRON/Desktop/MIC2SD/MIC2SD.srcs/sources_1/bd/design_1/ip/design_1_PDM_decoder_0_1/design_1_PDM_decoder_0_1.xci
# IP: The module: 'design_1_PDM_decoder_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/IRON/Desktop/MIC2SD/MIC2SD.srcs/sources_1/bd/design_1/ip/design_1_PDM_decoder_0_1/src/cic_compiler_0/cic_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_compiler_0 || ORIG_REF_NAME==cic_compiler_0} -quiet] -quiet

# IP: c:/Users/IRON/Desktop/MIC2SD/MIC2SD.srcs/sources_1/bd/design_1/ip/design_1_PDM_decoder_0_1/src/fir_compiler_0/fir_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet

# XDC: c:/Users/IRON/Desktop/MIC2SD/MIC2SD.srcs/sources_1/bd/design_1/ip/design_1_PDM_decoder_0_1/src/fir_compiler_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: C:/Users/IRON/Desktop/MIC2SD/MIC2SD.srcs/sources_1/bd/design_1/ip/design_1_PDM_decoder_0_1/design_1_PDM_decoder_0_1.xci
# IP: The module: 'design_1_PDM_decoder_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/IRON/Desktop/MIC2SD/MIC2SD.srcs/sources_1/bd/design_1/ip/design_1_PDM_decoder_0_1/src/cic_compiler_0/cic_compiler_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cic_compiler_0 || ORIG_REF_NAME==cic_compiler_0} -quiet] -quiet

# IP: c:/Users/IRON/Desktop/MIC2SD/MIC2SD.srcs/sources_1/bd/design_1/ip/design_1_PDM_decoder_0_1/src/fir_compiler_0/fir_compiler_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet

# XDC: c:/Users/IRON/Desktop/MIC2SD/MIC2SD.srcs/sources_1/bd/design_1/ip/design_1_PDM_decoder_0_1/src/fir_compiler_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
